import { test, describe } from "node:test";
import assert from "node:assert/strict";

import { makeReview, passAllSteps, StubSummaryProvider } from "./review-fakes";

/**
 * The summary port.
 *
 * No provider ships, so the shipped configuration is the one where none is
 * supplied — and that path must be the calm one, not a degraded one. Where a
 * provider *is* supplied, two properties carry the weight: nothing it produces
 * is recorded without the user handing it back, and what it produces is never
 * confusable with the user's own words.
 */

describe("with no provider — the shipped configuration", () => {
  test("no draft is available, and that is not an error", async () => {
    const { service } = makeReview();
    await passAllSteps(service);

    const draft = await service.draftSummary();
    assert.equal(draft.available, false);
    if (!draft.available) {
      assert.equal(draft.failure, undefined, "nothing failed — there is simply no provider");
    }
  });

  test("the review completes normally and records no summary", async () => {
    const { service } = makeReview();
    await passAllSteps(service);

    const result = await service.complete({ note: "my own words" });
    assert.ok(result.ok);
    if (result.ok) {
      assert.equal(result.review.summary, null);
      assert.equal(result.review.note, "my own words");
    }
  });
});

describe("with a provider supplied", () => {
  test("a draft is offered but nothing is written by asking for it", async () => {
    const provider = new StubSummaryProvider({ text: "the machine's account" });
    const { service, vault } = makeReview({ summary: provider });
    await passAllSteps(service);

    const before = vault.files.get("log/2026-W33.md");
    const draft = await service.draftSummary();

    assert.equal(draft.available, true);
    if (draft.available) {
      assert.equal(draft.text, "the machine's account");
      assert.equal(draft.provider, "stub-provider");
    }
    assert.equal(vault.files.get("log/2026-W33.md"), before, "drafting writes nothing");
  });

  test("a declined draft leaves the log exactly as it would have been", async () => {
    const provider = new StubSummaryProvider({ text: "unwanted" });

    const declined = makeReview({ summary: provider });
    await passAllSteps(declined.service);
    await declined.service.draftSummary();
    await declined.service.complete({ note: "mine" });

    const never = makeReview();
    await passAllSteps(never.service);
    await never.service.complete({ note: "mine" });

    assert.equal(
      declined.vault.files.get("log/2026-W33.md"),
      never.vault.files.get("log/2026-W33.md"),
      "declining costs nothing and leaves no trace",
    );
  });

  test("an accepted draft is attributed and kept separate from the note", async () => {
    const provider = new StubSummaryProvider({ text: "the machine's account" });
    const { service, vault } = makeReview({ summary: provider });
    await passAllSteps(service);

    const draft = await service.draftSummary();
    assert.ok(draft.available);
    if (!draft.available) return;

    const result = await service.complete({
      note: "my own words",
      summary: { text: draft.text, provider: draft.provider },
    });

    assert.ok(result.ok);
    if (result.ok) {
      assert.equal(result.review.note, "my own words");
      assert.equal(result.review.summary?.text, "the machine's account");
      assert.equal(result.review.summary?.provider, "stub-provider");
    }

    const content = vault.files.get("log/2026-W33.md") ?? "";
    assert.match(content, /## Summary \(generated by stub-provider\)/);
    assert.match(content, /## Note/);
    assert.ok(
      content.indexOf("my own words") !== content.indexOf("the machine's account"),
      "two sets of words, two places",
    );
  });

  test("a provider that throws never blocks completion", async () => {
    const provider = new StubSummaryProvider({ fail: "the API is down" });
    const { service } = makeReview({ summary: provider });
    await passAllSteps(service);

    const draft = await service.draftSummary();
    assert.equal(draft.available, false);
    if (!draft.available) assert.match(draft.failure ?? "", /API is down/);

    const result = await service.complete({ note: "still finished" });
    assert.ok(result.ok, "a failing provider cannot stop the ritual");
    if (result.ok) assert.equal(result.review.note, "still finished");
  });

  test("a provider that hangs and then fails is handled the same way", async () => {
    const provider = new StubSummaryProvider({ hang: true });
    const { service } = makeReview({ summary: provider });
    await passAllSteps(service);

    const draft = await service.draftSummary();
    assert.equal(draft.available, false);

    assert.ok((await service.complete({})).ok);
  });

  test("an empty draft records nothing rather than an empty section", async () => {
    const provider = new StubSummaryProvider({ text: "   \n " });
    const { service, vault } = makeReview({ summary: provider });
    await passAllSteps(service);

    assert.equal((await service.draftSummary()).available, false);

    await service.complete({ summary: { text: "  ", provider: "stub-provider" } });
    assert.doesNotMatch(vault.files.get("log/2026-W33.md") ?? "", /## Summary/);
  });

  test("the provider is asked only when the user asks for a draft", async () => {
    const provider = new StubSummaryProvider({ text: "unused" });
    const { service } = makeReview({ summary: provider });

    await passAllSteps(service);
    await service.complete({ note: "no draft wanted" });

    assert.equal(provider.calls, 0, "completing does not quietly invoke a provider");
  });
});
