import type { WeekId } from "../weekly/types";
import {
  REVIEW_STEPS,
  type AcceptedSummary,
  type InboxStepRecord,
  type ProjectReviewAction,
  type ProjectReviewRecord,
  type Review,
  type ReviewStepName,
  type ReviewSummary,
  type TopThreeStepRecord,
  type WaitingReviewRecord,
} from "./types";

/**
 * Reading and writing `log/YYYY-Www.md` — the weekly review, in progress and
 * finished.
 *
 * The same two rules that govern `projects/document.ts` and
 * `weekly/top-three-document.ts`:
 *
 *   1. **Parsing never fails.** An unknown section, prose under a heading, a
 *      hand-written line matching no grammar — all are carried through
 *      untouched and ignored by the reader. A file the app refuses to open is a
 *      file the app has taken hostage.
 *
 *   2. **Writing is surgical.** Only the lines being appended are added;
 *      everything else is reproduced byte for byte, because the vault is
 *      git-tracked and a read that reformats turns every app open into a diff.
 *
 * **On the third copy of section handling.** This module parses `##` sections
 * locally, as `top-three-document.ts` already does beside `projects/document.ts`.
 * The established habit here is a document module per document type, because
 * the semantics differ where it counts — this file has an in-progress marker,
 * per-step sections, and append-within-section writes that neither of the
 * others needs. **This is the third copy: when a fourth document type needs
 * section handling, extract `vault/markdown.ts` from all four at once rather
 * than adding a fifth** (research R11).
 *
 * The three, so a future fourth can find them all: `projects/document.ts`
 * (Feature 3), `weekly/top-three-document.ts` (Feature 4), and this file.
 * `waiting/waiting-document.ts` arrived with this feature and is deliberately
 * **not** a fourth — `waiting.md` has no `##` sections at all, so it shares the
 * two governing rules and none of the mechanism. Count copies of the section
 * code, not document modules.
 *
 * See specs/005-weekly-review-ritual/contracts/review-log-format.md
 */

export const LOG_DIR = "log";

export function reviewPath(week: WeekId): string {
  return `${LOG_DIR}/${week}.md`;
}

// ---------------------------------------------------------------------------
// Headings and grammar
// ---------------------------------------------------------------------------

export const INBOX_HEADING = "Inbox";
export const PROJECTS_HEADING = "Projects";
export const WAITING_HEADING = "Waiting for";
export const TOP_THREE_HEADING = "Top three";
export const NOTE_HEADING = "Note";
/** The provider's name lives in the heading, so attribution survives a grep. */
export const SUMMARY_HEADING_PREFIX = "Summary";

const H2 = /^##\s+(.+?)\s*$/;
const FIELD = /^\s*([A-Za-z][A-Za-z ]*?)\s*:\s?(.*)$/;
const TITLE = /^#\s+(.*)$/;

const DATE = String.raw`\d{4}-\d{2}-\d{2}`;

const INBOX_LINE = new RegExp(`^- (${DATE}) (?:inbox clear|(\\d+) items?, (\\w+), proceeded)$`);
const PROJECT_LINE = new RegExp(`^- (${DATE}) (\\S+) (.+)$`);
const WAITING_ITEM_LINE = new RegExp(
  `^- (${DATE}) @(\\S+) (\\d+)d (followed up|received|left) — (.*)$`,
);
const WAITING_PROJECT_LINE = new RegExp(
  `^- (${DATE}) project (\\S+) (\\d+)d left waiting$`,
);
const FINISHED_LINE = /^- finished: (.*)$/;
const SLIPPED_LINE = /^- slipped: (.*)$/;
const COMMITTED_LINE = /^- committed (\d{4}-W\d{2}): (.*)$/;
const SUMMARY_HEADING = /^Summary \(generated by (.+)\)$/;

// ---------------------------------------------------------------------------
// Locating things
// ---------------------------------------------------------------------------

/** Body range of a `## Heading`, exclusive of the heading itself. */
function sectionRange(
  lines: string[],
  heading: string,
): { head: number; start: number; end: number } | null {
  const head = lines.findIndex((l) => {
    const m = H2.exec(l);
    return m !== null && (m[1] ?? "").toLowerCase() === heading.toLowerCase();
  });
  if (head === -1) return null;

  let end = lines.length;
  for (let i = head + 1; i < lines.length; i++) {
    if (H2.test(lines[i] ?? "")) {
      end = i;
      break;
    }
  }
  return { head, start: head + 1, end };
}

/** The heading text of the first section whose name starts with `prefix`. */
function findHeading(lines: string[], prefix: string): string | null {
  for (const line of lines) {
    const m = H2.exec(line);
    const text = (m?.[1] ?? "").trim();
    if (m && text.toLowerCase().startsWith(prefix.toLowerCase())) return text;
  }
  return null;
}

function sectionLines(lines: string[], heading: string): string[] {
  const range = sectionRange(lines, heading);
  return range ? lines.slice(range.start, range.end) : [];
}

function sectionText(lines: string[], heading: string): string | null {
  const body = sectionLines(lines, heading).join("\n").trim();
  return body.length === 0 ? null : body;
}

function readField(lines: string[], key: string): string | null {
  for (const line of lines) {
    if (H2.test(line)) break;
    const m = FIELD.exec(line);
    if (m && (m[1] ?? "").trim().toLowerCase() === key.toLowerCase()) {
      const value = (m[2] ?? "").trim();
      return value.length === 0 ? null : value;
    }
  }
  return null;
}

// ---------------------------------------------------------------------------
// Creating
// ---------------------------------------------------------------------------

/**
 * A new review's file.
 *
 * Every section exists from the start, so a reader always sees the shape of the
 * ritual and an empty section means "nothing recorded here yet" rather than
 * "this file is malformed". `status` comes first because it is what a person
 * opening the file needs to know first.
 */
export function renderNewReview(week: WeekId, started: string): string {
  return [
    `# Weekly review ${week}`,
    "",
    "status: in progress",
    `started: ${started}`,
    "step: inbox",
    "",
    `## ${INBOX_HEADING}`,
    "",
    `## ${PROJECTS_HEADING}`,
    "",
    `## ${WAITING_HEADING}`,
    "",
    `## ${TOP_THREE_HEADING}`,
    "",
    `## ${NOTE_HEADING}`,
    "",
  ].join("\n");
}

// ---------------------------------------------------------------------------
// Reading
// ---------------------------------------------------------------------------

export function parseReview(content: string, week: WeekId): Review {
  const lines = content.split("\n");

  const statusRaw = (readField(lines, "status") ?? "in progress").toLowerCase();
  const summaryHeading = findHeading(lines, SUMMARY_HEADING_PREFIX);

  return {
    week,
    started: readField(lines, "started") ?? "",
    step: readStep(lines),
    // Anything that is not exactly "complete" reads as still in progress. A
    // half-typed status must not present an unfinished review as finished.
    status: statusRaw === "complete" ? "complete" : "in-progress",
    completed: readField(lines, "completed"),
    inbox: parseInboxRecords(sectionLines(lines, INBOX_HEADING))[0] ?? null,
    projects: parseProjectRecords(sectionLines(lines, PROJECTS_HEADING)),
    waiting: parseWaitingRecords(sectionLines(lines, WAITING_HEADING)),
    topThree: parseTopThreeRecord(sectionLines(lines, TOP_THREE_HEADING)),
    note: sectionText(lines, NOTE_HEADING),
    summary: parseSummary(lines, summaryHeading),
  };
}

export function parseReviewSummary(content: string, week: WeekId): ReviewSummary {
  const lines = content.split("\n");
  const statusRaw = (readField(lines, "status") ?? "in progress").toLowerCase();
  return {
    week,
    started: readField(lines, "started") ?? "",
    status: statusRaw === "complete" ? "complete" : "in-progress",
    completed: readField(lines, "completed"),
  };
}

function readStep(lines: string[]): ReviewStepName {
  const raw = (readField(lines, "step") ?? "").trim().toLowerCase();
  return REVIEW_STEPS.find((s) => s === raw) ?? "inbox";
}

function parseInboxRecords(lines: string[]): InboxStepRecord[] {
  const records: InboxStepRecord[] = [];
  for (const line of lines) {
    const m = INBOX_LINE.exec(line);
    if (!m) continue;
    const count = m[2] === undefined ? 0 : Number(m[2]);
    // The line reads "warned" because that is how it reads in English; the
    // verdict is `warn`. Mapped back rather than stored as written, so a record
    // read from the file is the same shape as one just decided — the two were
    // silently different until a round-trip test said so.
    records.push({
      count,
      verdict: m[3] === "blocked" ? "block" : m[3] === "warned" ? "warn" : "allow",
      on: m[1] ?? "",
      raw: line,
    });
  }
  return records;
}

function parseProjectRecords(lines: string[]): ProjectReviewRecord[] {
  const records: ProjectReviewRecord[] = [];
  for (const line of lines) {
    const m = PROJECT_LINE.exec(line);
    if (!m) continue;
    const rest = (m[3] ?? "").trim();
    const { action, detail } = readProjectAction(rest);
    records.push({ slug: m[2] ?? "", action, detail, on: m[1] ?? "", raw: line });
  }
  return records;
}

function readProjectAction(rest: string): { action: ProjectReviewAction; detail: string | null } {
  if (rest === "no change") return { action: "none", detail: null };
  if (rest.startsWith("status ")) return { action: "status", detail: rest.slice("status ".length) };
  if (rest.startsWith("milestone done ")) {
    return { action: "milestone-done", detail: rest.slice("milestone done ".length) };
  }
  if (rest.startsWith("next action ")) {
    return { action: "next-action", detail: rest.slice("next action ".length) };
  }
  // The three structure fixes the walk offers, in one shape. `milestones set`
  // is what adding a milestone to a flagged project records — the same fix, so
  // the same grammar rather than a fourth spelling.
  const structure = /^(outcome|dri|milestones) set$/.exec(rest);
  if (structure) return { action: "structure", detail: structure[1] ?? null };
  // An unrecognised action is still a record that the project was walked. The
  // file is the record, whoever wrote the line.
  return { action: "none", detail: rest };
}

function parseWaitingRecords(lines: string[]): WaitingReviewRecord[] {
  const records: WaitingReviewRecord[] = [];
  for (const line of lines) {
    const project = WAITING_PROJECT_LINE.exec(line);
    if (project) {
      records.push({
        text: "",
        owner: project[2] ?? "",
        days: Number(project[3] ?? 0),
        subject: "project",
        action: "none",
        on: project[1] ?? "",
        raw: line,
      });
      continue;
    }

    const item = WAITING_ITEM_LINE.exec(line);
    if (!item) continue;
    const word = item[4] ?? "left";
    records.push({
      text: item[5] ?? "",
      owner: item[2] ?? "",
      days: Number(item[3] ?? 0),
      subject: "item",
      action: word === "followed up" ? "followed-up" : word === "received" ? "received" : "none",
      on: item[1] ?? "",
      raw: line,
    });
  }
  return records;
}

function parseTopThreeRecord(lines: string[]): TopThreeStepRecord | null {
  const finished: string[] = [];
  const slipped: string[] = [];
  const committed: string[] = [];
  let forWeek: WeekId | null = null;

  for (const line of lines) {
    const f = FINISHED_LINE.exec(line);
    if (f) {
      finished.push(f[1] ?? "");
      continue;
    }
    const s = SLIPPED_LINE.exec(line);
    if (s) {
      slipped.push(s[1] ?? "");
      continue;
    }
    const c = COMMITTED_LINE.exec(line);
    if (c) {
      forWeek = c[1] ?? null;
      committed.push(c[2] ?? "");
    }
  }

  if (finished.length === 0 && slipped.length === 0 && committed.length === 0) return null;
  return { finished, slipped, committed, forWeek };
}

function parseSummary(lines: string[], heading: string | null): AcceptedSummary | null {
  if (heading === null) return null;
  const m = SUMMARY_HEADING.exec(heading);
  const text = sectionText(lines, heading);
  if (text === null) return null;
  return { text, provider: m?.[1] ?? "unknown" };
}

// ---------------------------------------------------------------------------
// Writing
// ---------------------------------------------------------------------------

/** Adds, updates, or removes one preamble `key: value` line. */
export function setPreambleField(content: string, key: string, value: string | null): string {
  const lines = content.split("\n");

  let existing = -1;
  let lastField = -1;
  for (let i = 0; i < lines.length; i++) {
    if (H2.test(lines[i] ?? "")) break;
    const m = FIELD.exec(lines[i] ?? "");
    if (!m) continue;
    lastField = i;
    if ((m[1] ?? "").trim().toLowerCase() === key.toLowerCase() && existing === -1) existing = i;
  }

  if (value === null) {
    if (existing !== -1) lines.splice(existing, 1);
    return lines.join("\n");
  }

  const line = `${key}: ${value}`;
  if (existing !== -1) {
    lines[existing] = line;
  } else if (lastField !== -1) {
    lines.splice(lastField + 1, 0, line);
  } else {
    const title = lines.findIndex((l) => TITLE.test(l));
    lines.splice(title + 1, 0, "", line);
  }
  return lines.join("\n");
}

/**
 * Appends one line to the end of a section's content.
 *
 * "End of content" rather than "end of section": the blank line separating this
 * section from the next is preserved, so appending never eats the spacing a
 * reader relies on, and the diff is exactly one line.
 */
export function appendToSection(content: string, heading: string, line: string): string {
  const lines = content.split("\n");
  const range = sectionRange(lines, heading);
  if (!range) {
    // A hand-edited file that lost the section: put it back rather than
    // dropping the record on the floor.
    const trimmed = [...lines];
    while (trimmed.length > 0 && (trimmed[trimmed.length - 1] ?? "").trim().length === 0) {
      trimmed.pop();
    }
    return [...trimmed, "", `## ${heading}`, "", line, ""].join("\n");
  }

  let at = range.end;
  while (at > range.start && (lines[at - 1] ?? "").trim().length === 0) at -= 1;
  lines.splice(at, 0, line);
  return lines.join("\n");
}

/** Replaces a section's body, creating the section at the end when absent. */
export function setSectionBody(content: string, heading: string, body: string): string {
  const lines = content.split("\n");
  const range = sectionRange(lines, heading);
  const bodyLines = body.split("\n");

  if (!range) {
    const trimmed = [...lines];
    while (trimmed.length > 0 && (trimmed[trimmed.length - 1] ?? "").trim().length === 0) {
      trimmed.pop();
    }
    return [...trimmed, "", `## ${heading}`, "", ...bodyLines, ""].join("\n");
  }

  let end = range.end;
  while (end > range.start && (lines[end - 1] ?? "").trim().length === 0) end -= 1;
  lines.splice(range.start, end - range.start, "", ...bodyLines);
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Line rendering — the grammar in contracts/review-log-format.md
// ---------------------------------------------------------------------------

export function renderInboxLine(on: string, count: number, verdict: string): string {
  if (count === 0) return `- ${on} inbox clear`;
  return `- ${on} ${count} item${count === 1 ? "" : "s"}, ${verdict}ed, proceeded`;
}

export function renderProjectLine(
  on: string,
  slug: string,
  action: ProjectReviewAction,
  detail: string | null,
): string {
  const body =
    action === "none"
      ? "no change"
      : action === "status"
        ? `status ${detail ?? ""}`
        : action === "milestone-done"
          ? `milestone done ${detail ?? ""}`
          : action === "next-action"
            ? `next action ${detail ?? "changed"}`
            : `${detail ?? "outcome"} set`;
  return `- ${on} ${slug} ${body}`;
}

export function renderWaitingItemLine(
  on: string,
  owner: string,
  days: number,
  action: WaitingReviewRecord["action"],
  text: string,
): string {
  const word = action === "followed-up" ? "followed up" : action === "received" ? "received" : "left";
  return `- ${on} @${owner} ${days}d ${word} — ${text}`;
}

export function renderWaitingProjectLine(on: string, slug: string, days: number): string {
  return `- ${on} project ${slug} ${days}d left waiting`;
}

export function renderTopThreeLines(record: TopThreeStepRecord): string[] {
  return [
    ...record.finished.map((t) => `- finished: ${t}`),
    ...record.slipped.map((t) => `- slipped: ${t}`),
    ...record.committed.map((t) => `- committed ${record.forWeek ?? ""}: ${t}`),
  ];
}

export function summaryHeadingFor(provider: string): string {
  return `${SUMMARY_HEADING_PREFIX} (generated by ${provider})`;
}
